# --- Stage 1: Builder ---
FROM python:3.12-slim AS builder
RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- Stage 2: Runner ---
FROM python:3.12-slim AS runner
WORKDIR /app

# Ye hain wo zaroori variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/opt/venv/bin:$PATH"

COPY --from=builder /opt/venv /opt/venv
COPY . .
RUN useradd -m appuser
USER appuser

EXPOSE 8000
CMD ["python", "main.py"]
